# Generated by Django 2.1.7 on 2019-03-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0002_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzashop',
            old_name='adress',
            new_name='address',
        ),
    ]
